# Update dependencies

version: 2
updates:
# Update the git submodules
- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - "dependencies"
  - "automerge"

# Update the Github Action versions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - "dependencies"
  - "automerge"
